language: rust
cache: cargo


matrix:
  include:
  - rust: stable
    script:
    - cargo test
  - rust: nightly-2018-12-04
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo test
    - cargo fmt --all -- --check

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
